package team.waitingcatch.app.restaurant.service.blacklist;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import lombok.RequiredArgsConstructor;
import team.waitingcatch.app.restaurant.dto.blacklist.CreateRequestBlackListEntityPassToBlackListEntityInTheBlackListService;
import team.waitingcatch.app.restaurant.dto.blacklist.CreateRequestBlackListEntityPassToBlackListEntityInTheRequestBlackListService;
import team.waitingcatch.app.restaurant.entity.BlackList;
import team.waitingcatch.app.restaurant.repository.BlackListRepository;

@Service
@RequiredArgsConstructor
@Transactional
public class BlackListServiceImpl implements BlackListService, InternalBlackListService {
	private final BlackListRepository blackListRepository;

	public void _createBlackList(
		CreateRequestBlackListEntityPassToBlackListEntityInTheRequestBlackListService
			createRequestBlackListEntityPassToBlackListEntityInTheRequestBlackListService) {
		CreateRequestBlackListEntityPassToBlackListEntityInTheBlackListService
			createRequestBlackListEntityPassToBlackListEntityInTheBlackListService = new
			CreateRequestBlackListEntityPassToBlackListEntityInTheBlackListService(
			createRequestBlackListEntityPassToBlackListEntityInTheRequestBlackListService);
		BlackList blackList = new BlackList(createRequestBlackListEntityPassToBlackListEntityInTheBlackListService);
		blackListRepository.save(blackList);
	}
}
